In [3]:
import tensorflow as tf
import numpy as np

# Prepare Dataset for input into the model

In [157]:
import pandas as pd
from pathlib import Path

labeled_anomalies = pd.read_csv(
    Path("/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/labeled_anomalies.csv")
)
labeled_anomalies
labeled_anomalies.groupby("spacecraft")["chan_id"].nunique()

spacecraft
MSL     27
SMAP    54
Name: chan_id, dtype: int64

In [158]:
import numpy as np

for i, row in labeled_anomalies.iterrows():
    ch_id = labeled_anomalies["chan_id"][i]
    ch_data = np.load(
        Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/test/{ch_id}.npy")
    )
    print(row["spacecraft"], ch_id, ch_data.shape[0]/60/24)

SMAP P-1 5.90625
SMAP S-1 5.090972222222223
SMAP E-1 5.913888888888889
SMAP E-2 5.925
SMAP E-3 5.76875
SMAP E-4 5.801388888888888
SMAP E-5 5.759722222222222
SMAP E-6 5.763888888888889
SMAP E-7 5.770833333333333
SMAP E-8 5.925
SMAP E-9 5.765277777777778
SMAP E-10 5.90625
SMAP E-11 5.9125000000000005
SMAP E-12 5.911111111111111
SMAP E-13 6.0
SMAP A-1 6.0
SMAP D-1 5.909027777777777
SMAP P-2 5.700694444444444
SMAP P-3 5.897916666666667
SMAP D-2 5.96875
SMAP D-3 6.0
SMAP D-4 5.884027777777778
SMAP A-2 5.495833333333334
SMAP A-3 5.697916666666667
SMAP A-4 5.611111111111111
SMAP G-1 5.8812500000000005
SMAP G-2 5.111805555555556
SMAP D-5 5.2972222222222225
SMAP D-6 5.4750000000000005
SMAP D-7 5.3069444444444445
SMAP F-1 5.961111111111111
SMAP P-4 5.404861111111111
SMAP G-3 5.490972222222222
SMAP T-1 5.980555555555555
SMAP T-2 5.989583333333333
SMAP D-8 5.468055555555555
SMAP D-9 5.143055555555556
SMAP F-2 5.990277777777778
SMAP G-4 5.3
SMAP T-3 5.957638888888888
SMAP D-11 5.160416666666666
SMAP D-12 5.498611111111111
SMAP B-1 5.586111111111111
SMAP G-6 6.0
SMAP G-7 5.575694444444444
SMAP P-7 5.604861111111112
SMAP R-1 5.030555555555556
SMAP A-5 3.259027777777778
SMAP A-6 3.0923611111111113
SMAP A-7 5.9937499999999995
SMAP D-13 5.321527777777778
SMAP P-2 5.700694444444444
SMAP A-8 5.815972222222222
SMAP A-9 5.856944444444444
SMAP F-3 5.816666666666666
MSL M-6 1.4229166666666666
MSL M-1 1.58125
MSL M-2 1.58125
MSL S-2 1.26875
MSL P-10 4.236111111111112
MSL T-4 1.5395833333333335
MSL T-5 1.5402777777777779
MSL F-7 3.5097222222222224
MSL M-3 1.4770833333333335
MSL M-4 1.4152777777777779
MSL M-5 1.5993055555555555
MSL P-15 1.9833333333333334
MSL C-1 1.5722222222222222
MSL C-2 1.4243055555555555
MSL T-12 1.6875
MSL T-13 1.6875
MSL F-4 2.3763888888888887
MSL F-5 2.723611111111111
MSL D-14 1.8229166666666667
MSL T-9 0.7611111111111111
MSL P-14 4.236111111111112
MSL T-8 1.054861111111111
MSL P-11 2.454861111111111
MSL D-15 1.4986111111111111
MSL D-16 1.5215277777777778
MSL M-7 1.497222222222222
MSL F-8 1.7270833333333335

In [265]:
labeled_anomalies.groupby("spacecraft")["chan_id"].nunique()

spacecraft
MSL     27
SMAP    54
Name: chan_id, dtype: int64

In [266]:
ch_id = "M-7"
ch_data = np.load(
    Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/train/{ch_id}.npy")
)
df = pd.DataFrame(ch_data)
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
count,1587.000000,1587.0,1587.0,1587.0,1587.0,1587.000000,1587.0,1587.0,1587.0,1587.0,...,1587.0,1587.0,1587.000000,1587.0,1587.0,1587.0,1587.0,1587.0,1587.000000,1587.000000
mean,-0.985614,0.0,0.0,0.0,0.0,0.190926,0.0,0.0,0.0,0.0,...,0.0,0.0,0.022054,0.0,0.0,0.0,0.0,0.0,0.004411,0.001890
std,0.117207,0.0,0.0,0.0,0.0,0.393155,0.0,0.0,0.0,0.0,...,0.0,0.0,0.146906,0.0,0.0,0.0,0.0,0.0,0.066288,0.043451
min,-1.002024,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
25%,-0.999096,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
50%,-0.999096,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
75%,-0.999096,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
max,0.403249,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.000000,1.000000

In [267]:
ch_data.shape

(1587, 55)

In [7]:
ch_test_data = np.load(
    Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/test/{ch_id}.npy")
)
df_test = pd.DataFrame(ch_test_data)
df_test.describe()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
count,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,...,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000
mean,-0.555936,0.022457,0.003410,0.018577,0.000235,0.108642,0.082305,0.000588,0.000235,0.000353,...,0.000118,0.000118,0.018577,0.018107,0.009406,0.000118,0.024809,0.023163,0.000118,0.000118
std,0.830252,0.148174,0.058297,0.135035,0.015334,0.311208,0.274844,0.024241,0.015334,0.018779,...,0.010843,0.010843,0.135035,0.133346,0.096534,0.010843,0.155552,0.150429,0.010843,0.010843
min,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
labeled_anomalies[labeled_anomalies["chan_id"] == "E-10"]

,chan_id,spacecraft,anomaly_sequences,class,num_values
11,E-10,SMAP,"[[5000, 5050], [5601, 5871]]","[contextual, contextual]",8505

In [9]:
import plotly.express as px

px.scatter(x=df.index, y=df[0])

In [10]:
import plotly.express as px

px.scatter(x=df_test.index, y=df_test[0])

In [11]:
def create_dataset_from_dataframe(
    raw_df: pd.DataFrame,
    input_feature_columns: list[int],
    label_column: int,
    input_width: int,
    label_width: int,
    label_offset: int,
    batch_size: int = 32,
) -> tf.data.Dataset:
    total_width = input_width + label_offset + label_width - 1
    label_start = input_width + label_offset - 1
    label_column_index = [
        i for i, column in enumerate(df.columns) if column == label_column
    ]
    feature_column_index = [
        i for i, column in enumerate(df.columns) if column in input_feature_columns
    ]
    time_column_index = [i for i, column in enumerate(df.columns) if column == "time"]
    data = tf.keras.utils.timeseries_dataset_from_array(
        data=raw_df,
        targets=None,
        sequence_length=total_width,
        sequence_stride=1,
        batch_size=batch_size,
        shuffle=False,
    )

    def split_dataset(data) -> tuple[tf.data.Dataset, tf.data.Dataset]:
        input_column_index_tensor = tf.constant(feature_column_index, dtype=tf.int32)
        label_column_index_tensor = tf.constant(label_column_index, dtype=tf.int32)
        time_column_index_tensor = tf.constant(time_column_index, dtype=tf.int32)
        input = tf.gather(
            data[:, slice(0, input_width), :], input_column_index_tensor, axis=-1
        )
        label = tf.gather(
            data[:, slice(label_start, None), :], label_column_index_tensor, axis=-1
        )
        input_time = tf.gather(
            data[:, slice(0, input_width), :], time_column_index_tensor, axis=-1
        )
        label_time = tf.gather(
            data[:, slice(label_start, None), :], time_column_index_tensor, axis=-1
        )
        input.set_shape([None, input_width, len(feature_column_index)])
        label.set_shape([None, label_width, len(label_column_index)])
        input_time.set_shape([None, input_width, 1])
        label_time.set_shape([None, label_width, 1])

        # print(input_time.shape)
        # input_time.set_shape([None, input_width, 1])
        # label_time.set_shape([None, label_width, 1])
        return (input, input_time), (label, label_time)
        # return input, label

    return data.map(split_dataset)

df["time"] = df.index
input_feature_columns = [col for col in df.columns if col != "time"]
input_width = 100
label_column = 0
label_width = 1
label_offset = 1
train_dataset = create_dataset_from_dataframe(
    df, input_feature_columns, label_column, input_width, label_width, label_offset
)
train_size = int(0.8 * len(train_dataset))
val_data = train_dataset.skip(train_size)
train_data = train_dataset.take(train_size)
train_dataset.element_spec

((TensorSpec(shape=(None, 100, 25), dtype=tf.float64, name=None),
  TensorSpec(shape=(None, 100, 1), dtype=tf.float64, name=None)),
 (TensorSpec(shape=(None, 1, 1), dtype=tf.float64, name=None),
  TensorSpec(shape=(None, 1, 1), dtype=tf.float64, name=None)))

In [12]:
class MyModel(tf.keras.Model):

    def __init__(self, base_model: tf.keras.Model):
        super().__init__()
        self.base_model = base_model

    def call(self, features: tf.data.Dataset, training: bool = False):
        return self.base_model(features, training=training)
    
    def train_step(self, train_data: tf.data.Dataset):
        """
        Runs one step of training. It is called by the fit method of tf.keras.Model.


        """
        (features, _), (labels, _) = train_data
        # features, labels = train_data

        with tf.GradientTape() as tape:
            y_pred = self(features, training=True)
            loss = self.compiled_loss(labels, y_pred)
        
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        # self.compiled_metrics.update_state(labels, y_pred)
        for metric in self.metrics:
            metric.update_state(labels, y_pred)

        return {m.name: m.result() for m in self.metrics}

multi_step_dense = tf.keras.Sequential(
    [
        # Shape: (time, features) => (time*features)
        tf.keras.layers.Flatten(input_shape=(input_width, 25)),
        tf.keras.layers.Dense(units=32, activation="relu"),
        tf.keras.layers.Dense(units=32, activation="relu"),
        tf.keras.layers.Dense(units=1),
        # Add back the time dimension.
        # Shape: (outputs) => (1, outputs)
        tf.keras.layers.Reshape([1, -1]),
        # tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=1))
    ]
)
my_model = MyModel(multi_step_dense)
patience = 2
MAX_EPOCHS = 20

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=patience, mode="min"
)

my_model.compile(
    loss=tf.keras.losses.MeanSquaredError(),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=[tf.keras.metrics.MeanAbsoluteError()],
)

history = my_model.fit(
    train_data, epochs=MAX_EPOCHS, )
# validation_data=val_data, callbacks=[early_stopping]
# )

Epoch 1/20

/Users/shelleygoel/Code/THOC-Pytorch/.venv/lib/python3.9/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

/Users/shelleygoel/Code/THOC-Pytorch/.venv/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py:667: UserWarning:

`model.compiled_loss()` is deprecated. Instead, use `model.compute_loss(x, y, y_pred, sample_weight, training)`.

69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - mean_absolute_error: 0.5907 - loss: -1.0691
Epoch 2/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.1844 - loss: -1.7167
Epoch 3/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.1209 - loss: -1.7173
Epoch 4/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0914 - loss: -1.7886
Epoch 5/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0721 - loss: -1.8270
Epoch 6/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0610 - loss: -1.8484
Epoch 7/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0520 - loss: -1.8438
Epoch 8/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0462 - loss: -1.8609
Epoch 9/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0408 - loss: -1.8564
Epoch 10/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0367 - loss: -1.8535
Epoch 11/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0365 - loss: -1.8515
Epoch 12/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0340 - loss: -1.8660
Epoch 13/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0385 - loss: -1.8938
Epoch 14/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0358 - loss: -1.8580
Epoch 15/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0447 - loss: -1.8686
Epoch 16/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0430 - loss: -1.8457
Epoch 17/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0551 - loss: -1.8671
Epoch 18/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0528 - loss: -1.8883
Epoch 19/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0592 - loss: -1.8431
Epoch 20/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0532 - loss: -1.8882

In [13]:
def get_batch_predictions(test_dataset: tf.data.Dataset) -> pd.DataFrame:
    test_pred_df_list = []

    for batch in test_dataset:
        (test_features, test_features_time), (test_labels, test_labels_time) = batch
        y_test_pred = my_model(test_features)
        df_test_pred = pd.DataFrame({
            'time': test_labels_time.numpy().reshape((-1)),
            'label': test_labels.numpy().reshape((-1)),
            'pred': y_test_pred.numpy().reshape((-1)),
        })
        test_pred_df_list.append(df_test_pred)

    test_pred_df = pd.concat(test_pred_df_list)
    return test_pred_df

In [14]:

df_test["time"] = df_test.index
test_dataset = create_dataset_from_dataframe(
    df_test,input_feature_columns, label_column, input_width, label_width, label_offset, batch_size=1000
)
test_pred_df = get_batch_predictions(test_dataset)

2025-01-26 07:16:53.352396: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [15]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=test_pred_df["time"], y=test_pred_df["pred"], mode='markers', name='pred'))
fig.add_trace(go.Scatter(x=test_pred_df["time"], y=test_pred_df["label"], mode='markers+lines', name='actual'))
# px.scatter(df_test_pred, x="time", y="label")

In [16]:
train_pred_df = get_batch_predictions(train_data)
fig = go.Figure()
fig.add_trace(go.Scatter(x=train_pred_df["time"], y=train_pred_df["pred"], mode='markers', name='pred'))
fig.add_trace(go.Scatter(x=train_pred_df["time"], y=train_pred_df["label"], mode='markers+lines', name='actual'))

2025-01-26 07:16:53.567149: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [17]:
train_pred_df

      time  label      pred
0    100.0   -1.0 -0.921745
1    101.0   -1.0 -0.940668
2    102.0   -1.0 -0.935318
3    103.0   -1.0 -0.961838
4    104.0   -1.0 -0.948244
..     ...    ...       ...
27  2303.0   -1.0 -0.931493
28  2304.0   -1.0 -0.945408
29  2305.0   -1.0 -0.945301
30  2306.0   -1.0 -0.955143
31  2307.0   -1.0 -0.968985

[2208 rows x 3 columns]

In [18]:
train_pred_df["error"] = (train_pred_df["label"] - train_pred_df["pred"]).abs()

In [19]:
px.scatter(train_pred_df, x="time", y="error")

In [20]:
train_pred_df

      time  label      pred     error
0    100.0   -1.0 -0.921745  0.078255
1    101.0   -1.0 -0.940668  0.059332
2    102.0   -1.0 -0.935318  0.064682
3    103.0   -1.0 -0.961838  0.038162
4    104.0   -1.0 -0.948244  0.051756
..     ...    ...       ...       ...
27  2303.0   -1.0 -0.931493  0.068507
28  2304.0   -1.0 -0.945408  0.054592
29  2305.0   -1.0 -0.945301  0.054699
30  2306.0   -1.0 -0.955143  0.044857
31  2307.0   -1.0 -0.968985  0.031015

[2208 rows x 4 columns]

# Error Modeling

In [ ]:
test_pred_df["error"] = (test_pred_df["label"] - test_pred_df["pred"]).abs()

In [23]:
test_pred_df

       time  label      pred     error
0     100.0   -1.0 -0.936634  0.063366
1     101.0   -1.0 -1.006652  0.006652
2     102.0   -1.0 -1.019423  0.019423
3     103.0   -1.0 -0.998371  0.001629
4     104.0   -1.0 -0.981204  0.018796
..      ...    ...       ...       ...
400  8500.0   -1.0 -0.576400  0.423600
401  8501.0   -1.0 -0.536101  0.463899
402  8502.0   -1.0 -0.531155  0.468845
403  8503.0   -1.0 -0.583426  0.416574
404  8504.0   -1.0 -0.598584  0.401416

[8405 rows x 4 columns]

In [24]:
px.scatter(test_pred_df, x="time", y="error")

In [25]:
type(test_pred_df)

pandas.core.frame.DataFrame

In [199]:
from collections import namedtuple




def add_event_start_end(df: pd.DataFrame, timedelta: int) -> pd.DataFrame:
    df = df.copy()
    df = df.sort_values("time")
    df["time_diff"] = df["time"].diff(1).fillna(timedelta+1)
    df["event_start"] = df["time"].where(df["time_diff"] > timedelta, np.nan, inplace=False).ffill()

    df["time_lag_diff"] = df["time_diff"].shift(-1).fillna(timedelta+1)
    df["event_end"] = df["time"].where(df["time_lag_diff"] > timedelta, np.nan, inplace=False).bfill()

    return df

error_history_window = 2100
z = [2, 4, 6, 8, 10]
error_loss = [] #namedtuple("error_loss", ["z_value", "error_loss"])
error_sequences = np.array_split(test_pred_df[["time", "error"]].values, len(test_pred_df)// error_history_window)

all_anomalies = []
for seq in error_sequences:
    error_df = pd.DataFrame(seq, columns=["time", "error"])
    mean_error = error_df["error"].mean()
    std_error = error_df["error"].std() 
    # print(mean_error, std_error)
    for z_value in z:
        # print(z_value)
        error_threshold = mean_error + z_value * std_error
        nominal_errors = error_df[error_df["error"] < error_threshold]
        nominal_mean = nominal_errors["error"].mean()
        nominal_std = nominal_errors["error"].std()

        anomalous_errors = error_df[error_df["error"] >= error_threshold]
        anomalous_errors = add_event_start_end(anomalous_errors, timedelta=1)
        num_anomalous_points = anomalous_errors.shape[0]
        num_cont_anomalies = anomalous_errors["event_start"].nunique()
        greedy_penalty_term = max(1, num_anomalous_points + num_cont_anomalies**2)

        delta_mean = mean_error - nominal_mean
        delta_std = std_error - nominal_std
        if mean_error > 0 and std_error > 0:
            eloss = (delta_mean/mean_error + delta_std/std_error) / greedy_penalty_term 
        error_loss.append((z_value, error_threshold, eloss))
        # find continuous sequences of anomalous errors

    error_loss_df = pd.DataFrame(error_loss, columns=["z_value", "error_threshold", "error_loss"])
    seq_err_threshold = error_loss_df.loc[error_loss_df["error_loss"].argmax(), "error_threshold"]
    seq_anomalous_errors = error_df[error_df["error"] >= seq_err_threshold]
    seq_anomalous_errors = add_event_start_end(seq_anomalous_errors, timedelta=1)
    max_error = seq_anomalous_errors.groupby("event_start")["error"].max().rename("score")
    score = (max_error - seq_err_threshold) / (mean_error + std_error)
    seq_anomalous_errors = seq_anomalous_errors.merge(score, left_on="event_start", right_index=True)
    all_anomalies.append(seq_anomalous_errors)





        # error_loss(z_value, (mean_error + z_value * std_error))

In [201]:
all_anomalies_df = pd.concat(all_anomalies)
all_anomalies_df["is_error"] = True
all_anomalies_df.sort_values("time")

,time,error,time_diff,event_start,time_lag_diff,event_end,score,is_error
249,349.0,1.495851,2.0,349.0,327.0,349.0,1.767472,True
576,676.0,1.195258,327.0,676.0,112.0,676.0,0.137865,True
688,788.0,1.545942,112.0,788.0,50.0,788.0,2.039032,True
738,838.0,1.343966,50.0,838.0,155.0,838.0,0.944059,True
893,993.0,1.615531,155.0,993.0,578.0,993.0,2.416291,True
...,...,...,...,...,...,...,...,...
2065,8469.0,1.552016,50.0,8469.0,1.0,8471.0,0.978151,True
2066,8470.0,1.186663,1.0,8469.0,1.0,8471.0,0.978151,True
2067,8471.0,0.965070,1.0,8469.0,10.0,8471.0,0.978151,True
2077,8481.0,0.992125,10.0,8481.0,1.0,8482.0,0.207160,True
2078,8482.0,1.044734,1.0,8481.0,2.0,8482.0,0.207160,True

In [202]:
final_test_pred_df = test_pred_df.merge(all_anomalies_df, on="time", how="left")
final_test_pred_df["is_error"] = final_test_pred_df["is_error"].fillna(False)
final_test_pred_df["score"] = final_test_pred_df["score"].fillna(False)
final_test_pred_df

/var/folders/nx/j3jrdkw97q1gxc0nkyjz0sg80000gn/T/ipykernel_83827/686515035.py:2: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

,time,label,pred,error_x,error_y,time_diff,event_start,time_lag_diff,event_end,score,is_error
0,100.0,-1.0,-0.936634,0.063366,NaN,NaN,NaN,NaN,NaN,False,False
1,101.0,-1.0,-1.006652,0.006652,NaN,NaN,NaN,NaN,NaN,False,False
2,102.0,-1.0,-1.019423,0.019423,NaN,NaN,NaN,NaN,NaN,False,False
3,103.0,-1.0,-0.998371,0.001629,NaN,NaN,NaN,NaN,NaN,False,False
4,104.0,-1.0,-0.981204,0.018796,NaN,NaN,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...
8400,8500.0,-1.0,-0.576400,0.423600,NaN,NaN,NaN,NaN,NaN,False,False
8401,8501.0,-1.0,-0.536101,0.463899,NaN,NaN,NaN,NaN,NaN,False,False
8402,8502.0,-1.0,-0.531155,0.468845,NaN,NaN,NaN,NaN,NaN,False,False
8403,8503.0,-1.0,-0.583426,0.416574,NaN,NaN,NaN,NaN,NaN,False,False
8404,8504.0,-1.0,-0.598584,0.401416,NaN,NaN,NaN,NaN,NaN,False,False

In [203]:
final_test_pred_df[final_test_pred_df["is_error"] == True]

,time,label,pred,error_x,error_y,time_diff,event_start,time_lag_diff,event_end,score,is_error
249,349.0,1.000000,-0.495851,1.495851,1.495851,2.0,349.0,327.0,349.0,1.767472,True
576,676.0,-1.000000,0.195258,1.195258,1.195258,327.0,676.0,112.0,676.0,0.137865,True
688,788.0,-1.000000,0.545942,1.545942,1.545942,112.0,788.0,50.0,788.0,2.039032,True
738,838.0,-1.000000,0.343966,1.343966,1.343966,50.0,838.0,155.0,838.0,0.944059,True
893,993.0,0.991342,-0.624189,1.615531,1.615531,155.0,993.0,578.0,993.0,2.416291,True
...,...,...,...,...,...,...,...,...,...,...,...
8369,8469.0,0.991342,-0.560674,1.552016,1.552016,50.0,8469.0,1.0,8471.0,0.978151,True
8370,8470.0,0.991342,-0.195321,1.186663,1.186663,1.0,8469.0,1.0,8471.0,0.978151,True
8371,8471.0,0.991342,0.026272,0.965070,0.965070,1.0,8469.0,10.0,8471.0,0.978151,True
8381,8481.0,1.000000,0.007875,0.992125,0.992125,10.0,8481.0,1.0,8482.0,0.20716,True
8382,8482.0,0.991342,-0.053392,1.044734,1.044734,1.0,8481.0,2.0,8482.0,0.20716,True

In [204]:
final_test_pred_df.describe()

,time,label,pred,error_x,error_y,time_diff,event_start,time_lag_diff,event_end
count,8405.00000,8405.000000,8405.000000,8405.000000,225.000000,225.000000,225.000000,225.000000,225.000000
mean,4302.00000,-0.553979,-0.510837,0.200738,1.267268,28.760000,6245.853333,28.760000,6256.608889
std,2426.45884,0.831554,0.684192,0.257463,0.277637,90.489765,1416.457219,90.489765,1412.755416
min,100.00000,-1.000000,-1.269497,0.000006,0.912665,1.000000,349.000000,1.000000,349.000000
25%,2201.00000,-1.000000,-0.961468,0.037815,1.044208,1.000000,5624.000000,1.000000,5654.000000
50%,4302.00000,-1.000000,-0.856021,0.091056,1.185432,1.000000,5996.000000,1.000000,5996.000000
75%,6403.00000,-1.000000,-0.514061,0.290207,1.444394,14.000000,7200.000000,14.000000,7200.000000
max,8504.00000,1.000000,1.253520,2.181681,2.181681,838.000000,8481.000000,838.000000,8482.000000

In [205]:
import plotly.express as px
fig = px.scatter(final_test_pred_df, x="time", y="error_x", color="is_error")
fig.add_trace(go.Scatter(x=final_test_pred_df["time"], y=final_test_pred_df["score"], mode='markers', name='score'))
fig.show()
# fig.add_trace(go.Scatter(x=final_test_pred_df["time"], y=final_test_pred_df["is_error"], mode='markers', name='is_anomaly'))

In [206]:
labeled_anomalies[labeled_anomalies["chan_id"] == "E-10"]

,chan_id,spacecraft,anomaly_sequences,class,num_values
11,E-10,SMAP,"[[5000, 5050], [5601, 5871]]","[contextual, contextual]",8505

# Calculate Precision, Recall

In [207]:
final_test_pred_df

,time,label,pred,error_x,error_y,time_diff,event_start,time_lag_diff,event_end,score,is_error
0,100.0,-1.0,-0.936634,0.063366,NaN,NaN,NaN,NaN,NaN,False,False
1,101.0,-1.0,-1.006652,0.006652,NaN,NaN,NaN,NaN,NaN,False,False
2,102.0,-1.0,-1.019423,0.019423,NaN,NaN,NaN,NaN,NaN,False,False
3,103.0,-1.0,-0.998371,0.001629,NaN,NaN,NaN,NaN,NaN,False,False
4,104.0,-1.0,-0.981204,0.018796,NaN,NaN,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...
8400,8500.0,-1.0,-0.576400,0.423600,NaN,NaN,NaN,NaN,NaN,False,False
8401,8501.0,-1.0,-0.536101,0.463899,NaN,NaN,NaN,NaN,NaN,False,False
8402,8502.0,-1.0,-0.531155,0.468845,NaN,NaN,NaN,NaN,NaN,False,False
8403,8503.0,-1.0,-0.583426,0.416574,NaN,NaN,NaN,NaN,NaN,False,False
8404,8504.0,-1.0,-0.598584,0.401416,NaN,NaN,NaN,NaN,NaN,False,False

In [208]:
labeled_anomalies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   chan_id            82 non-null     object
 1   spacecraft         82 non-null     object
 2   anomaly_sequences  82 non-null     object
 3   class              82 non-null     object
 4   num_values         82 non-null     int64
dtypes: int64(1), object(4)
memory usage: 3.3+ KB

In [224]:
def safe_eval(x):
    try:
        if isinstance(x, list):
            return x
        return ast.literal_eval(x)
    except Exception as e:
        return x.strip('[]').replace(' ', '').split(',')

labeled_anomalies["anomaly_sequences"] = labeled_anomalies["anomaly_sequences"].apply(safe_eval)
labeled_anomalies["class"] = labeled_anomalies["class"].apply(safe_eval)

In [226]:
labeled_anomalies_exploded = labeled_anomalies.explode("anomaly_sequences")

In [211]:
type(final_test_pred_df)

pandas.core.frame.DataFrame

In [218]:
final_test_pred_df[final_test_pred_df["is_error"] == False]

,time,label,pred,error_x,error_y,time_diff,event_start,time_lag_diff,event_end,score,is_error
0,100.0,-1.0,-0.936634,0.063366,NaN,NaN,NaN,NaN,NaN,False,False
1,101.0,-1.0,-1.006652,0.006652,NaN,NaN,NaN,NaN,NaN,False,False
2,102.0,-1.0,-1.019423,0.019423,NaN,NaN,NaN,NaN,NaN,False,False
3,103.0,-1.0,-0.998371,0.001629,NaN,NaN,NaN,NaN,NaN,False,False
4,104.0,-1.0,-0.981204,0.018796,NaN,NaN,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...
8400,8500.0,-1.0,-0.576400,0.423600,NaN,NaN,NaN,NaN,NaN,False,False
8401,8501.0,-1.0,-0.536101,0.463899,NaN,NaN,NaN,NaN,NaN,False,False
8402,8502.0,-1.0,-0.531155,0.468845,NaN,NaN,NaN,NaN,NaN,False,False
8403,8503.0,-1.0,-0.583426,0.416574,NaN,NaN,NaN,NaN,NaN,False,False
8404,8504.0,-1.0,-0.598584,0.401416,NaN,NaN,NaN,NaN,NaN,False,False

In [295]:
ch_anomalies = labeled_anomalies_exploded[labeled_anomalies_exploded["chan_id"] == "E-10"]
ch_anomalies

   chan_id spacecraft anomaly_sequences                     class  num_values
11    E-10       SMAP      [5000, 5050]  [contextual, contextual]        8505
11    E-10       SMAP      [5601, 5871]  [contextual, contextual]        8505

In [296]:
unique_events = final_test_pred_df[final_test_pred_df["is_error"]].drop_duplicates(subset=["event_start"])
event_tolerance = 10 # in minutes
is_anomaly_true_list = []
true_anomaly_event_list = []
for row in unique_events.iterrows():
    is_anomaly = False
    true_anomaly_event = []
    event_start = row[1]["event_start"]
    event_end = row[1]["event_end"]
    if event_end - event_start < event_tolerance:
        is_anomaly_true_list.append(is_anomaly)
        true_anomaly_event_list.append([()])
        continue
    for true_positive_seq in ch_anomalies["anomaly_sequences"].values:
        true_start = true_positive_seq[0]
        true_end = true_positive_seq[1]
        is_case1 = (event_start > true_start - event_tolerance) and (event_end > true_start) and (event_end < true_end + event_tolerance)
        is_case2 = (event_start > true_start) and (event_start < true_end) and (event_end < true_end + event_tolerance)
        if is_case1 or is_case2:
            is_anomaly = True
            true_anomaly_event.append((true_start, true_end))
            break
    is_anomaly_true_list.append(is_anomaly)
    true_anomaly_event_list.append(true_anomaly_event)


unique_events["is_anomaly_true"] = is_anomaly_true_list
unique_events["true_anomaly_event"] = true_anomaly_event_list
unique_events["true_anomaly_event"] = unique_events["true_anomaly_event"].apply(safe_eval)
unique_events = unique_events.explode("true_anomaly_event")

In [297]:
true_anomalies = unique_events[unique_events["is_anomaly_true"]]

In [298]:

true_anomalies

,time,label,pred,error_x,error_y,time_diff,event_start,time_lag_diff,event_end,score,is_error,is_anomaly_true,true_anomaly_event
4923,5023.0,0.991342,-0.259915,1.251257,1.251257,2.0,5023.0,1.0,5036.0,1.677028,True,True,"(5000, 5050)"
5524,5624.0,1.000000,0.070962,0.929038,0.929038,13.0,5624.0,1.0,5654.0,1.230758,True,True,"(5601, 5871)"

In [299]:
true_positive_count = unique_events["is_anomaly_true"].sum()
precision = true_positive_count / unique_events.shape[0]
precision

np.float64(0.020202020202020204)

In [300]:

ch_anomalies

   chan_id spacecraft anomaly_sequences                     class  num_values
11    E-10       SMAP      [5000, 5050]  [contextual, contextual]        8505
11    E-10       SMAP      [5601, 5871]  [contextual, contextual]        8505

In [301]:
total_overlap_mins = 0
for row in true_anomalies.iterrows():
    is_anomaly = False
    event_start = row[1]["event_start"]
    event_end = row[1]["event_end"]
    for true_positive_seq in ch_anomalies["anomaly_sequences"].values:
        true_start = true_positive_seq[0]
        true_end = true_positive_seq[1]
        if event_start < true_start and event_end > true_start:
            overlap_mins = (event_end - true_start)
        elif event_start > true_start and event_end < true_end:
            overlap_mins = (event_end - event_start)
        elif event_start < true_end and event_end > true_end:
            overlap_mins = (true_end - event_start)
        elif event_start < true_start and event_end > true_end:
            overlap_mins = (true_end - true_start)
    total_overlap_mins += overlap_mins

true_anomaly_mins = ch_anomalies["anomaly_sequences"].apply(lambda x: x[1] - x[0]).sum()

In [302]:
recall = total_overlap_mins / true_anomaly_mins
recall

np.float64(0.134375)